{{- if .Values.memcached_results.enabled -}}
{{- if .Values.memcached_results.podDisruptionBudget -}}
apiVersion: {{ include "mimir.podDisruptionBudget.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "memcached-results") }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "memcached-results") | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mimir.selectorLabels" (dict "ctx" . "component" "memcached-results") | nindent 6 }}
{{ toYaml .Values.memcached_results.podDisruptionBudget | indent 2 }}
{{- end -}}
{{- end -}}
